version: '3.0'
services:

  databasedev:
    image: postgres:16.0
    container_name: db_dev
    ports:
      - "5432:5432"
    volumes:
      - ./dataForTesting:/var/lib/management/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: management
