version: '3.8'
services:

  databasedev:
    image: postgres:16.0
    container_name: db_dev
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: management